// ==========================================
// 1. EVENTOS ATIVOS (Futuros ou a Decorrer)
// ==========================================
export const events = [
  {
    "title": "Actualización en Medicina Personalizada",
    "date": "1 Outubro 2026 – 15 Junho 2027",
    "category": "Genética Molecular",
    "type": "Curso online",
    "price": "70 € sócios / 95 € não sócios",
    "certificate": "Consultar organização",
    "organizer": "Sociedad Española de Medicina de Laboratorio (SEMEDLAB)",
    "link": "https://formacion.semedlab.es/",
    "region": "Online",
    "description": "Formação avançada para profissionais de saúde, com 8 módulos especializados e fórum de discussão com especialistas. Inscrição até 1 de novembro de 2026."
  },
  {
    "title": "Biolog Webinar — Consistent Anaerobic Culture Results",
    "date": "16 Junho 2026",
    "category": "Microbiologia / Infeção",
    "type": "Webinar online",
    "price": "Consultar",
    "certificate": "Consultar organização",
    "organizer": "Biolog / RapidMicrobiology",
    "link": "https://www.rapidmicrobiology.com/",
    "region": "Online",
    "description": "Webinar dedicado a cultura anaeróbia, microbiologia clínica e métodos de cultura."
  },
  {
    "title": "Webinar | Hemocromatose",
    "date": "24 Junho 2026, 18h30",
    "category": "Hematologia",
    "type": "Webinar gratuito / online",
    "price": "Gratuito",
    "certificate": "Consultar organização",
    "organizer": "Ordem dos Farmacêuticos — Colégio de Análises Clínicas e Genética Humana",
    "link": "https://www.ordemfarmaceuticos.pt/",
    "region": "Online",
    "description": "Webinar sobre hemocromatose, diagnóstico laboratorial e genética humana."
  },
  {
    "title": "ADLM — Urines get no respect: From afterthought to asset in diagnostic stewardship",
    "date": "24 Junho 2026",
    "category": "Qualidade",
    "type": "Webinar",
    "price": "Consultar",
    "certificate": "Consultar organização",
    "organizer": "ADLM",
    "link": "https://myadlm.org/",
    "region": "Online",
    "description": "Webinar focado na gestão diagnóstica e controlo de qualidade na análise de urina."
  },
  {
    "title": "New Rapid Microbial Testing System with Results in Hours",
    "date": "25 Junho 2026",
    "category": "Microbiologia / Infeção",
    "type": "Webinar online",
    "price": "Gratuito",
    "certificate": "Consultar organização",
    "organizer": "RapidMicrobiology",
    "link": "https://www.rapidmicrobiology.com/",
    "region": "Online",
    "description": "Apresentação de novas tecnologias laboratoriais para identificação rápida de microrganismos."
  },
  {
    "title": "13.ª Conferência Europeia sobre Doenças Raras e Medicamentos Órfãos",
    "date": "3–4 Junho 2026",
    "category": "Doenças Raras",
    "type": "Conferência",
    "price": "Consultar",
    "certificate": "Sim",
    "organizer": "EURORDIS",
    "link": "https://www.eurordis.org/",
    "region": "Europa / Online",
    "description": "Espaço de debate sobre políticas públicas, diagnóstico e novos tratamentos para doenças raras."
  },
  {
    "title": "Boas práticas no exame de urina de rotina em laboratório",
    "date": "13 Agosto 2026",
    "category": "Qualidade",
    "type": "Webinar online",
    "price": "Consultar",
    "certificate": "Sim",
    "organizer": "ProMeQuaLab",
    "link": "Plataforma ProMeQuaLab",
    "region": "Online",
    "description": "Sessão dedicada à padronização e boas práticas no exame básico de urina."
  },
  {
    "title": "20th International Conference on Pathology and Laboratory Medicine",
    "date": "7–8 Setembro 2026",
    "category": "Medicina Laboratorial",
    "type": "Conferência Internacional",
    "price": "Consultar",
    "certificate": "Sim",
    "organizer": "WALS",
    "link": "https://wals.org/",
    "region": "Espanha / Online",
    "description": "Encontro internacional sobre avanços globais em patologia e medicina laboratorial."
  },
  {
    "title": "PAM 2026 — Porto's Autoimmune Meeting",
    "date": "1–3 Outubro 2026",
    "category": "Autoimunidade",
    "type": "Reunião Científica",
    "price": "Consultar",
    "certificate": "Sim",
    "organizer": "Grupo de Estudos de Autoimunidade",
    "link": "https://www.portoautoimmunemeeting.pt/",
    "region": "Porto, Portugal",
    "description": "Discussão e atualização clínica sobre patologias autoimunes e diagnóstico de anticorpos."
  },
  {
    "title": "Análise Computacional e Bioinformática de Variantes em Doença Genética",
    "date": "12–16 Outubro 2026",
    "category": "Genética Molecular",
    "type": "Curso Prático",
    "price": "Consultar",
    "certificate": "Sim",
    "organizer": "Faculdade de Ciências da Universidade de Lisboa",
    "link": "https://ciencias.ulisboa.pt/",
    "region": "Lisboa, Portugal",
    "description": "Formação avançada em ferramentas bioinformáticas para classificação de variantes genéticas."
  },
  {
    "title": "18.ª Reunião Científica da SPML",
    "date": "29–31 Outubro 2026",
    "category": "Medicina Laboratorial",
    "type": "Reunião Presencial",
    "price": "Consultar",
    "certificate": "Sim",
    "organizer": "Sociedade Portuguesa de Medicina Laboratorial (SPML)",
    "link": "https://www.spml.pt/",
    "region": "Portugal",
    "description": "Encontro de outono para apresentação de trabalhos científicos e debate técnico."
  },
  {
    "title": "Reunião Anual da Sociedade Portuguesa de Hematologia 2026",
    "date": "5–7 Novembro 2026",
    "category": "Hematologia",
    "type": "Reunião Nacional",
    "price": "Consultar",
    "certificate": "Sim",
    "organizer": "SPH",
    "link": "https://www.sph.pt/",
    "region": "Portugal",
    "description": "O principal fórum de discussão nacional de hematologia laboratorial e clínica."
  },
  {
    "title": "Programa de Formação Avançada em Hematologia",
    "date": "Setembro 2025 – Julho 2027",
    "category": "Hematologia",
    "type": "Pós-Graduação / Curso contínuo",
    "price": "Consultar",
    "certificate": "Sim",
    "organizer": "Faculdade de Medicina de Lisboa",
    "link": "https://www.medicina.ulisboa.pt/",
    "region": "Lisboa, Portugal",
    "description": "Programa modular e de longa duração cobrindo todas as vertentes da hematologia analítica."
  },
  {
    "title": "Curso de Antibioterapia | 18.ª Edição",
    "date": "16–20 Novembro 2026",
    "category": "Microbiologia / Infeção",
    "type": "Curso Intensivo",
    "price": "Consultar",
    "certificate": "Sim",
    "organizer": "Hospital da Luz Learning Health",
    "link": "https://learninghealth.hospitaldaluz.pt/",
    "region": "Lisboa, Portugal",
    "description": "Curso dedicado à utilização de antibioterapia e atualização crítica em infeção."
  },
  {
    "title": "30.ª Reunião Anual da Sociedade Portuguesa de Genética Humana",
    "date": "19–21 Novembro 2026",
    "category": "Genética Molecular",
    "type": "Reunião científica presencial",
    "price": "Consultar inscrição",
    "certificate": "Consultar organização",
    "organizer": "Sociedade Portuguesa de Genética Humana (SPGH)",
    "link": "https://spgh.net/",
    "region": "Lisboa, Portugal",
    "description": "Reunião científica dedicada à genética humana e genómica clínica."
  },
  {
    "title": "EHA Scientific Meetings & Webinar Activities 2026",
    "date": "Ao longo de 2026",
    "category": "Hematologia",
    "type": "Série contínua de webinars e sessões online",
    "price": "Consultar",
    "certificate": "Consultar organização",
    "organizer": "European Hematology Association (EHA)",
    "link": "https://ehaweb.org/",
    "region": "Online",
    "description": "Série de webinars e sessões online sobre leucemias, linfomas, hemostase, hemoglobinopatias e hematologia clínica."
  },
  {
    "title": "EHA Scientific Meetings & Webinar Activities 2026 — Hemostase",
    "date": "Ao longo de 2026",
    "category": "Coagulação e Hemostase",
    "type": "Série contínua de webinars e sessões online",
    "price": "Consultar",
    "certificate": "Consultar organização",
    "organizer": "European Hematology Association (EHA)",
    "link": "https://ehaweb.org/",
    "region": "Online",
    "description": "Sessões da EHA relevantes para hemostase, coagulação, trombose e hematologia clínica."
  },
  {
    "title": "Curso em Aspetos Éticos e Sociais em Genética Clínica Laboratorial — 5.ª edição",
    "date": "2026",
    "category": "Genética Molecular",
    "type": "Curso online",
    "price": "Consultar inscrição",
    "certificate": "Consultar organization",
    "organizer": "Faculdade de Medicina da Universidade de Coimbra",
    "link": "https://www.uc.pt/fmuc/",
    "region": "Online",
    "description": "Curso sobre interpretação de variantes, aconselhamento genético e ética laboratorial."
  },
  {
    "title": "Webinar | Da lâmina ao diagnóstico: o poder da Imunohistoquímica na anatomia patológica",
    "date": "15 Junho 2026, 19h00",
    "category": "Anatomia Patológica",
    "type": "Webinar online",
    "price": "Gratuito (Inscrição obrigatória)",
    "certificate": "Sim",
    "organizer": "MedLab Calendar (LinkedIn)",
    "link": "https://lnkd.in/dm6vFXc4",
    "region": "Online",
    "description": "Webinar focado na transformação da patologia, abordando o papel fundamental da imunohistoquímica desde a preparação da lâmina até ao diagnóstico final."
  },
  {
    "title": "Curso Fase Preanalítica en el Laboratorio Clínico",
    "date": "Período letivo 2026 - 2027",
    "category": "Qualidade",
    "type": "Curso online",
    "price": "Consultar",
    "certificate": "Sim",
    "organizer": "SEMEDLAB",
    "link": "https://semedlab.es/curso/curso-fase-preanalitica-laboratorio-clinico/",
    "region": "Online",
    "description": "Curso focado no controlo de qualidade, boas práticas, identificação e minimização de erros na fase pré-analítica do laboratório clínico."
  },
  {
    "title": "Curso de Casos Clínicos de Biología Hematológica",
    "date": "Período letivo 2026 - 2027",
    "category": "Hematologia",
    "type": "Curso online",
    "price": "Consultar",
    "certificate": "Sim",
    "organizer": "SEMEDLAB",
    "link": "https://semedlab.es/curso/casos-clinicos-de-biologia-hematologica/",
    "region": "Online",
    "description": "Discussão prática e interativa de casos clínicos reais no âmbito da hematologia laboratorial e biológica."
  },
  {
    "title": "Curso de Bioestadística Básica Aplicada a las Ciencias de la Salud",
    "date": "Período letivo 2026 - 2027",
    "category": "Qualidade",
    "type": "Curso online",
    "price": "Consultar",
    "certificate": "Sim",
    "organizer": "SEMEDLAB",
    "link": "https://semedlab.es/curso/curso-de-bioestadistica-basica-aplicada-a-las-ciencias-de-la-salud/",
    "region": "Online",
    "description": "Formação em conceitos essenciais de bioestatística aplicada à investigação clínica, análise de dados de saúde e publicações científicas."
  },
  {
    "title": "Gestión de Riesgos y Calidad en Pruebas en el Lugar de Atención al Paciente (POCT)",
    "date": "Período letivo 2026 - 2027",
    "category": "Qualidade",
    "type": "Curso online",
    "price": "Consultar",
    "certificate": "Sim",
    "organizer": "SEMEDLAB",
    "link": "https://semedlab.es/curso/gestion-riesgos-calidad-pruebas-lugar-atencion-paciente-poct/",
    "region": "Online",
    "description": "Curso focado no planeamento, controlo de qualidade e gestão de risco aplicados aos testes laboratoriais descentralizados junto ao paciente (POCT)."
  },
  {
    "title": "Taller de Procesos Asistenciales en Enfermedad Renal Crónica (ERC)",
    "date": "Período letivo 2026 - 2027",
    "category": "Bioquímica Clínica",
    "type": "Workshop / Taller online",
    "price": "Consultar",
    "certificate": "Sim",
    "organizer": "SEMEDLAB",
    "link": "https://semedlab.es/curso/taller-procesos-asistenciales-erc/",
    "region": "Online",
    "description": "Workshop técnico focado na otimização e uniformização dos processos assistenciais e diagnóstico laboratorial na Doença Renal Crónica."
  },
  {
    "title": "Casos clínicos de hemostasia vinculados a pruebas de laboratorio: cómo los tests facilitan el diagnóstico",
    "date": "22 Junho 2026, 16h00 - 18h00",
    "category": "Coagulação e Hemostase",
    "type": "Webinar online",
    "price": "Consultar",
    "certificate": "Solicitada acreditação SEAFORMEC",
    "organizer": "Sociedad Española de Trombosis y Hemostasia (SETH)",
    "link": "https://seth.es/formacion/casos-clinicos-hemostasia-vinculados-pruebas-laboratorio/",
    "region": "Online",
    "description": "1º Webinar da 5ª Edição do Programa Formativo para o Laboratório de Hemostasia. Curvas de reação em TTPa, diagnóstico de anticoagulante lúpico, défice de FXIII e doença de von Willebrand."
  },
  {
    "title": "Webinar: Accelerated diagnostic chest pain protocols; evidence and pitfalls in implementation",
    "date": "9 Junho 2026",
    "category": "Qualidade",
    "type": "Webinar online",
    "price": "Gratuito / Acessível",
    "certificate": "Sim",
    "organizer": "EFLM",
    "link": "https://www.eflm.eu/",
    "region": "Online",
    "description": "Protocolos de dor torácica no laboratório de urgência (Troponinas de alta sensibilidade)."
  },
  {
    "title": "Webinar: The role of angiogenetic factors in placental disorders",
    "date": "23 Junho 2026",
    "category": "Bioquímica Clínica",
    "type": "Webinar online",
    "price": "Gratuito / Acessível",
    "certificate": "Sim",
    "organizer": "EFLM",
    "link": "https://www.eflm.eu/",
    "region": "Online",
    "description": "Biomarcadores laboratoriais na pré-eclâmpsia e distúrbios da placenta."
  },
  {
    "title": "Webinar: Laboratory Insights into Neurological Disorders: Spinal Cord and Alzheimer's Disease",
    "date": "7 Julho 2026",
    "category": "Bioquímica Clínica",
    "type": "Webinar online",
    "price": "Gratuito / Acessível",
    "certificate": "Sim",
    "organizer": "EFLM",
    "link": "https://www.eflm.eu/",
    "region": "Online",
    "description": "O papel crescente do laboratório clínico no diagnóstico precoce da Doença de Alzheimer (Biomarcadores no LCR e plasma)."
  },
  {
    "title": "2.ªs Jornadas Prof. Margarida Lima — Mieloma Múltiplo: teoria e prática",
    "date": "19 Junho 2026",
    "category": "Hematologia",
    "type": "Presencial",
    "price": "Consultar",
    "certificate": "Sim",
    "organizer": "APsa & Grupo Português de Mieloma Múltiplo",
    "link": "Consultar Redes Sociais / LinkedIn",
    "region": "Forte de São Francisco, Chaves",
    "description": "Jornadas dedicadas ao Mieloma Múltiplo abrangendo diagnóstico laboratorial, casos clínicos interativos, tratamento com células CAR-T e perspetivas futuras."
  },
  {
    "title": "Reuniões de Casos Clínicos de Mieloma Múltiplo",
    "date": "Última segunda-feira de cada mês",
    "category": "Hematologia",
    "type": "Reunião virtual / Online",
    "price": "Gratuito",
    "certificate": "Não aplicável",
    "organizer": "Grupo Português de Mieloma Múltiplo (GPMM)",
    "link": "Consultar GPMM / LinkedIn",
    "region": "Online",
    "description": "Reunião mensal virtual aberta a profissionais de saúde para discussão de casos clínicos práticos de Mieloma Múltiplo."
  },
  {
    "title": "EFISG: Difficult and Curious Fungal Diseases Clinical Cases",
    "date": "17 Novembro 2026, 13h00",
    "category": "Microbiologia / Infeção",
    "type": "Webinar via Zoom",
    "price": "Consultar",
    "certificate": "Sim",
    "organizer": "ESCMID Fungal Infection Study Group (EFISG)",
    "link": "https://www.escmid.org/",
    "region": "Online",
    "description": "Discussão de casos clínicos complexos e curiosos de doenças fúngicas."
  },
  {
    "title": "IMPACT-ICU: Infection management and prevention - advances and current trends for intensive care unit patients",
    "date": "Novembro 2026",
    "category": "Microbiologia / Infeção",
    "type": "Curso / Webinar online",
    "price": "Consultar",
    "certificate": "Sim",
    "organizer": "ESCMID",
    "link": "https://www.escmid.org/",
    "region": "Online",
    "description": "Formação avançada focada na prevenção e gestão de infeções em ambiente de cuidados intensivos (UCI)."
  },
  {
    "title": "Workshop: Os Impactos da Inteligência Artificial para a Genética e Genómica",
    "date": "A confirmar (2026)",
    "category": "Genética Molecular",
    "type": "Workshop online",
    "price": "Consultar",
    "certificate": "Sim",
    "organizer": "Consultar Organização (LinkedIn Feed)",
    "link": "LinkedIn Feed",
    "region": "Online",
    "description": "Abordagem sobre as novas tendências, desafios e aplicações da Inteligência Artificial na medicina de precisão, genética e genómica."
  },
  {
    "title": "HEMO 2026 — Congresso Brasileiro de Hematologia, Hemoterapia e Terapia Celular",
    "date": "28 a 31 Outubro 2026",
    "category": "Hematologia",
    "type": "Congresso Presencial",
    "price": "Consultar",
    "certificate": "Sim",
    "organizer": "Associação Brasileira de Hematologia (ABHH)",
    "link": "https://abhh.org.br/",
    "region": "Riocentro, Rio de Janeiro, Brasil",
    "description": "Um dos maiores congressos da América Latina em hematologia, abordando novos avanços, terapia celular e medicina transfusional."
  },
  {
    "title": "IUMS 2026 — Congresso Internacional de Microbiologia em Lisboa",
    "date": "04 a 06 Novembro 2026",
    "category": "Microbiologia / Infeção",
    "type": "Congresso Presencial",
    "price": "Consultar",
    "certificate": "Sim",
    "organizer": "International Union of Microbiological Societies (IUMS)",
    "link": "https://www.iums2026.com/",
    "region": "Centro de Congressos de Lisboa (CCL), Portugal",
    "description": "Grande congresso internacional reunindo os principais especialistas mundiais em virologia, bacteriologia e micologia."
  },
  {
    "title": "Formação ProMeQuaLab: Diagnóstico da Rubéola",
    "date": "22 Junho 2026",
    "category": "Microbiologia / Infeção",
    "type": "Webinar online",
    "price": "Consultar",
    "certificate": "Sim",
    "organizer": "PNAEQ / ProMeQuaLab",
    "link": "Plataforma ProMeQuaLab",
    "region": "Online",
    "description": "Sessão formativa com a palestrante Paula Palminha sobre as diretrizes laboratoriais e abordagens no diagnóstico da Rubéola."
  },
  {
    "title": "Formação ProMeQuaLab: Sistema de Gestão da Qualidade",
    "date": "13 Julho 2026",
    "category": "Qualidade",
    "type": "Webinar online",
    "price": "Consultar",
    "certificate": "Sim",
    "organizer": "PNAEQ / ProMeQuaLab",
    "link": "Plataforma ProMeQuaLab",
    "region": "Online",
    "description": "Formação focada na implementação e melhoria do sistema de gestão da qualidade em laboratórios de saúde, com a palestrante Carmen Aguiar."
  },
  {
    "title": "Formação ProMeQuaLab: Boas práticas na execução do exame de urina de rotina",
    "date": "13 Agosto 2026",
    "category": "Qualidade",
    "type": "Webinar online",
    "price": "Consultar",
    "certificate": "Sim",
    "organizer": "PNAEQ / ProMeQuaLab",
    "link": "Plataforma ProMeQuaLab",
    "region": "Online",
    "description": "Sessão de esclarecimento sobre urinálise e boas práticas na execução do exame básico de urina, com a palestrante Michelle Lima Garcez."
  },
  {
    "title": "Formação ProMeQuaLab: Desempenho dos participantes do PNAEQ — Morfologia sangue periférico (2020-2024)",
    "date": "24 Setembro 2026",
    "category": "Hematologia",
    "type": "Webinar online",
    "price": "Consultar",
    "certificate": "Sim",
    "organizer": "PNAEQ / ProMeQuaLab",
    "link": "Plataforma ProMeQuaLab",
    "region": "Online",
    "description": "Análise retrospetiva e discussão do desempenho global no controlo de qualidade externo de morfologia hematológica, com a palestrante Cláudia Flores."
  }
];

// ==========================================
// 2. ARQUIVO DE EVENTOS (Já Decorridos)
// ==========================================
export const archivedEvents = [
  {
    "title": "9º Encontro Nacional de Diagnóstico Pré-Natal",
    "date": "12-13 Fevereiro 2026",
    "category": "Genética Molecular",
    "type": "Encontro Presencial",
    "price": "Consultar",
    "certificate": "Sim",
    "organizer": "SPG",
    "link": "https://www.spg.pt",
    "region": "Portugal",
    "description": "Encontro focado nos avanços em diagnóstico pré-natal e genética médica."
  },
  {
    "title": "Webinar: Inteligência Artificial no Laboratório Clínico",
    "date": "26 Fevereiro 2026",
    "category": "Qualidade",
    "type": "Webinar online",
    "price": "Gratuito",
    "certificate": "Sim",
    "organizer": "SPQC",
    "link": "https://www.spqc.pt",
    "region": "Online",
    "description": "Aplicações e impacto da inteligência artificial nas análises clínicas."
  },
  {
    "title": "Curso Prático de Citometria de Fluxo Hematológica",
    "date": "05-06 Março 2026",
    "category": "Hematologia",
    "type": "Curso Presencial",
    "price": "Consultar",
    "certificate": "Sim",
    "organizer": "IPOLFG",
    "link": "https://www.ipolisboa.min-saude.pt",
    "region": "Lisboa, Portugal",
    "description": "Abordagem prática da citometria de fluxo aplicada a patologias hematológicas."
  },
  {
    "title": "12º Congresso Nacional de Medicina Laboratorial",
    "date": "19-21 Março 2026",
    "category": "Medicina Laboratorial",
    "type": "Congresso Presencial",
    "price": "Consultar",
    "certificate": "Sim",
    "organizer": "SPML",
    "link": "https://www.spml.pt",
    "region": "Portugal",
    "description": "Grande congresso nacional de medicina laboratorial e análises clínicas."
  },
  {
    "title": "Webinar: Atualização em Marcadores Cardíacos",
    "date": "09 Abril 2026",
    "category": "Bioquímica Clínica",
    "type": "Webinar online",
    "price": "Gratuito",
    "certificate": "Sim",
    "organizer": "AACC Europe",
    "link": "https://www.aacc.org",
    "region": "Online",
    "description": "Revisão sobre o papel dos biomarcadores cardíacos na urgência e rotina."
  },
  {
    "title": "Jornadas de Primavera de Doenças Infeciosas",
    "date": "23-24 Abril 2026",
    "category": "Microbiologia / Infeção",
    "type": "Jornadas Presenciais",
    "price": "Consultar",
    "certificate": "Sim",
    "organizer": "SPMI",
    "link": "https://www.spmi.pt",
    "region": "Portugal",
    "description": "Discussão multidisciplinar de patologia infeciosa e diagnóstico microbiológico."
  },
  {
    "title": "Workshop: Validação de Métodos segundo a ISO 15189:2022",
    "date": "07 Maio 2026",
    "category": "Qualidade",
    "type": "Workshop Presencial",
    "price": "Consultar",
    "certificate": "Sim",
    "organizer": "RELACRE",
    "link": "https://www.relacre.pt",
    "region": "Lisboa, Portugal",
    "description": "Sessão prática focada nos requisitos de validação da nova norma ISO 15189."
  },
  {
    "title": "Simpósio Ibero-Americano de Erros Inatos do Metabolismo",
    "date": "14-15 Maio 2026",
    "category": "Bioquímica Clínica",
    "type": "Simpósio Presencial",
    "price": "Consultar",
    "certificate": "Sim",
    "organizer": "Insa",
    "link": "https://www.insa.min-saude.pt",
    "region": "Lisboa, Portugal",
    "description": "Rastreio e novas abordagens diagnósticas em doenças metabólicas raras."
  },
  {
    "title": "Webinar: Automação e Futuro da Microbiologia",
    "date": "28 Maio 2026",
    "category": "Microbiologia / Infeção",
    "type": "Webinar online",
    "price": "Gratuito",
    "certificate": "Sim",
    "organizer": "BD Biosciences",
    "link": "https://www.bd.com",
    "region": "Online",
    "description": "Sistemas automatizados de hemoculturas e identificação rápida."
  }
];
